### ISSUE TITLE
Using content addresses, why they matter.

### ISSUE THREAD

**Issue by mokuki082** [MatrixAI/Emergence#18]
NPM Problem: "Kite" and leftpad.

**Comment by CMCDragonkai** [comment]
Content addresses you mean?

**Comment by CMCDragonkai** [comment]
This can probably be closed once you have the Nix stuff down.

**Comment by mokuki082** [comment]
Oops yeah, it was a typo.

**Comment by mokuki082** [comment]
Closing this issue after research on [Nix's philosophy and their approach of achieveing content addressibility in the build environment](https://github.com/MatrixAI/Emergence/blob/master/language/nix/2018:04:24:nix.md). The hashing implementation is explored as documented [here](https://github.com/MatrixAI/Emergence/blob/master/language/nix/2018:5:05:nix-pills-read.md#nix-derivations).
