### ISSUE TITLE
First Emergence Article

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Emergence#3]
Due for 31st March. @mokuki082 Please fill in a proposal for this month.

**Comment by CMCDragonkai** [comment]
Articles about Docker, Container Runtimes, Container Networking, Virtual Machines, Kernel Programming, CI/CD

**Comment by mokuki082** [comment]
Proposal: Linux network namespaces using iproute2 (I may include some discussion on alternative methods with net-tools and why iproute2 is usually better).

**Comment by mokuki082** [comment]
Finished article draft, waiting for review.
