### ISSUE TITLE
FFI with Maps or Containers

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Emergence#32]
The more complex data structures that require mapping between Haskell and Go shouldn't involve a map in the intermediate C. Whatever exists in C should be a very simple structure that carries pointers. Most likely an array of some sort.

I imagine a Haskell Map to a go function expecting a Go Map. Then the Haskell map needs to be serialised (as some sort of array of pointers), and those pointers must then be used to construct the Go map. However we have to be careful about mutability. If the go function mutates things not expected by Haskell, there could be segfaults. Further investigation here needed.

**Comment by CMCDragonkai** [comment]
Alternatively rather than directly sending a Haskell map to Go. Expose Go functions that mutate that Map back to Haskell, and Haskell only calls those functions rather than directly working on the Map. That reduces the amount of copying that exists, and keeps the memory local the Go environment.

**Comment by CMCDragonkai** [comment]
I split off the issue about bidirectional transformation to https://github.com/MatrixAI/Emergence/issues/33 I realised that this was an issue I thought about a long time ago that will be relevant, hopefully we do not need to get that deep to solve this problem.

**Comment by mokuki082** [comment]
Closing this because we no longer bind into libcontainer, hence serialising map isn't the top concern.
