### ISSUE TITLE
Translate artifacts to OCI runtime

### ISSUE THREAD

**Issue by mokuki082** [MatrixAI/Emergence#37]
When the Artifact expression is interpreted, it should be translated into some determinisitic output, which contains information of image layers, configuration, and other metadata. This determinisitic output then needs to be translated into OCI runtime spec and root fs in order to be deployed by RunC.

This issue will be focusing on two deliverables:
1. Code to translate artifact config to runtime config
2. Code to extract image layer information into an usable filesystem (rootfs).

**Comment by mokuki082** [comment]
[OCI image spec to OCI runtime spec](https://github.com/opencontainers/image-spec/blob/master/conversion.md)

**Comment by n-zhang-hp** [comment]
[oci-image-tool](https://github.com/opencontainers/image-tools) can be used for image validation, unpacking image, and creating a runtime bundle.

Runtime configuration still need to be further supplied into the generated config.json. 

Right now it needs to be run as root when unpacking or creating runtime bundle due to ociTools creating image with uid/gid 0.

**Comment by CMCDragonkai** [comment]
Docker build tools in Nix doesn't use docker, so no need to contact docker daemon. It places it in its own directory unlike runc so permissions are possible. See how it does it?

**Comment by CMCDragonkai** [comment]
It uses QEMU as well I think.

**Comment by n-zhang-hp** [comment]
Currently using [oci image-tools](https://github.com/opencontainers/image-tools) to unpack and create root filesystem and configuration from image layout. However, `oci-image-tool create` does not pass `exposedPorts` from image config to runtime config as annotation.

Need to extract and maintain this somehow while building oci-based artifacts

**Comment by n-zhang-hp** [comment]
`1` is now tracked by #57 
`2` is done via oci-image-tool for now
