### ISSUE TITLE
Creating composition of primitives

### ISSUE THREAD

**Issue by mokuki082** [MatrixAI/Emergence#6]
Practice creating composition of primitives using low level C, shell or Haskell.

**Comment by mokuki082** [comment]
I have created a shell process with isolated namespaces using C and mainly the `clone` function. 

Here is the [source code](https://github.com/MatrixAI/container-practices/blob/73c25ab6cc1b1f06280f6157a49e4f776ae223dd/pid-experiments/practice.c).

My next goal is to complete this container by isolating the filesystem (using `chroot`) and then mounting the `proc` directory under the changed root. This would also involve researching how container images are bundled.

I will also look into USER namespace and how to allow root privileges for this container.

**Comment by CMCDragonkai** [comment]
Remember to see how to do this from Haskell too

On 21 March 2018 12:45:19 GMT+11:00, Moku <notifications@github.com> wrote:
>I have created a shell process with isolated namespaces using C and
>mainly the `clone` function. 
>
>Here is the [source
>code](https://github.com/MatrixAI/container-practices/blob/73c25ab6cc1b1f06280f6157a49e4f776ae223dd/pid-experiments/practice.c).
>
>My next goal is to complete this container by isolating the filesystem
>(using `chroot`) and then mounting the `proc` directory under the
>changed root. This would also involve researching how container images
>are bundled.
>
>I will also look into USER namespace and how to allow root privileges
>for this container.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/Emergence/issues/6#issuecomment-374813199

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mokuki082** [comment]
Sure, so far I've got a pretty good idea of how it works in C. I'll try doing it in Haskell soon.

**Comment by mokuki082** [comment]
Closing this as we are utilising RunC as our containe runtime, hence it's not necessary to create composition of primitives in Haskell.
